{{- if and (.Release.IsInstall) (.Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grader-api.postgresqlSecretName" . }}
data:
  password: {{ randAlphaNum 24 | b64enc }}
  postgres-password: {{ randAlphaNum 24 | b64enc }}
{{- end }}