{{- if and (.Release.IsInstall) (.Values.rabbitmq.enabled) }}
{{- if not (lookup "v1" "Secret" .Release.Namespace (include "grader-api.rabbitmqSecretName" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grader-api.rabbitmqSecretName" . }}
  annotations:
    helm.sh/resource-policy: keep
data:
  {{- $rabbitmqPassword := (randAlphaNum 24 | b64enc) }}
  rabbitmq-password: {{ $rabbitmqPassword }}
  BROKER_PASSWORD: {{ $rabbitmqPassword }}
{{- end }}
{{- end }}