{{- if and (.Release.IsInstall) (.Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grader-api.postgresqlSecretName" . }}
  annotations:
    helm.sh/resource-policy: keep
data:
  password: {{ randAlphaNum 24 | b64enc }}
  {{- $postgresPasswd := (randAlphaNum 24 | b64enc) }}
  postgres-password: {{ $postgresPasswd }}
  POSTGRES_PASSWORD: {{ $postgresPasswd }}
{{- end }}