{{- if and (.Release.IsInstall) (.Values.redis.enabled) }}
{{- if not (lookup "v1" "Secret" .Release.Namespace (include "grader-api.redisSecretName" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grader-api.redisSecretName" . }}
  annotations:
    helm.sh/resource-policy: keep
data:
  {{- $redisPassword := (randAlphaNum 24 | b64enc) }}
  redis-password: {{ $redisPassword }}
  BROKER_PASSWORD: {{ $redisPassword }}
{{- end }}
{{- end }}