{{- if .Values.serviceAccount.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "grader-api.fullname" . }}-role
rules:
- apiGroups:
  - ""
  resources:
    - pods
    - secrets
  verbs:
    - get
    - create
    - delete
{{- end }}