{{- if .Values.serviceAccount.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "grader-api.fullname" . }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "grader-api.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "grader-api.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}