{{- if and (.Values.config.enabled) (.Values.config.secretData) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grader-api.fullname" . }}
stringData:
  {{- toYaml .Values.config.secretData | nindent 2 }}
{{- end }}